//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelRehberi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON
    {
        public int Identity { get; set; }
        public string PersonName { get; set; }
        public string PersonSurname { get; set; }
        public System.DateTime Birthdate { get; set; }
        public string Email { get; set; }
        public string PhoneNumber1 { get; set; }
        public string PhoneNumber2 { get; set; }
        public System.DateTime HireDate { get; set; }
        public string Picture { get; set; }
        public int DepartmentId { get; set; }
        public int TitleId { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual TITLE TITLE { get; set; }
    }
}
